# Generated by Django 5.2 on 2025-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название пряжи', max_length=50)),
                ('origin', models.CharField(help_text='Введите происхождение пряжи', max_length=50)),
                ('price', models.IntegerField(help_text='Введите цену пряжи')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
